application:
  axon:
    snapshot:
      threshold: 100
spring:
  application:
    name: account-command 
  datasource:
    url: jdbc:h2:../db-command;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  quartz:
    job-store-type: jdbc
logging:
  level: 
    root: error
#    org.axonframework: debug
#    org.springframework.transaction: debug
#    org.springframework.orm.jpa: debug
axon:
  metrics:
    auto-configuration:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

---
spring:
  profiles: jdbc
  datasource:
    initialization-mode: ALWAYS
    platform: jdbc
      
---        
spring:
  profiles: rabbit
axon:
  amqp:
    transaction-mode: publisher-ack
    exchange: account.events
   
---
spring:
  profiles: kafka
axon:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: account-command
    default-topic: account.events
    properties:
      security.protocol: PLAINTEXT
    producer:
      transaction-id-prefix: account        #Enables kafka's transaction support
    
