CREATE TABLE IF NOT EXISTS "DOMAINEVENTENTRY"(
    "GLOBALINDEX" BIGINT NOT NULL,
    "EVENTIDENTIFIER" VARCHAR(255) NOT NULL,
    "METADATA" BLOB,
    "PAYLOAD" BLOB NOT NULL,
    "PAYLOADREVISION" VARCHAR(255),
    "PAYLOADTYPE" VARCHAR(255) NOT NULL,
    "TIMESTAMP" VARCHAR(255) NOT NULL,
    "AGGREGATEIDENTIFIER" VARCHAR(255) NOT NULL,
    "SEQUENCENUMBER" BIGINT NOT NULL,
    "TYPE" VARCHAR(255)
);             
ALTER TABLE "DOMAINEVENTENTRY" ADD CONSTRAINT IF NOT EXISTS "PKDOMAINEVENTENTRY" PRIMARY KEY("GLOBALINDEX");  
     
CREATE TABLE IF NOT EXISTS "SNAPSHOTEVENTENTRY"(
    "AGGREGATEIDENTIFIER" VARCHAR(255) NOT NULL,
    "SEQUENCENUMBER" BIGINT NOT NULL,
    "TYPE" VARCHAR(255) NOT NULL,
    "EVENTIDENTIFIER" VARCHAR(255) NOT NULL,
    "METADATA" BLOB,
    "PAYLOAD" BLOB NOT NULL,
    "PAYLOADREVISION" VARCHAR(255),
    "PAYLOADTYPE" VARCHAR(255) NOT NULL,
    "TIMESTAMP" VARCHAR(255) NOT NULL
);      
ALTER TABLE "SNAPSHOTEVENTENTRY" ADD CONSTRAINT IF NOT EXISTS "PKSNAPSHOTEVENTENTRY" PRIMARY KEY("AGGREGATEIDENTIFIER", "SEQUENCENUMBER", "TYPE");                  
ALTER TABLE "DOMAINEVENTENTRY" ADD CONSTRAINT IF NOT EXISTS "UKAGGREGATE" UNIQUE("AGGREGATEIDENTIFIER", "SEQUENCENUMBER");             
ALTER TABLE "DOMAINEVENTENTRY" ADD CONSTRAINT IF NOT EXISTS "UKEVENT" UNIQUE("EVENTIDENTIFIER");   
ALTER TABLE "SNAPSHOTEVENTENTRY" ADD CONSTRAINT IF NOT EXISTS "UKSNAPSHOTEVENT" UNIQUE("EVENTIDENTIFIER"); 
