server:
  port: 8082
spring:
  application:
    name: account-query-info
  datasource:
    url: jdbc:h2:../db-info;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
logging:
  level:
    root: error
#    org.axonframework: debug
axon:
  metrics:
    auto-configuration:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 
          - metrics
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
            
---
spring:
  profiles: rabbit
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
application:
  exchange: account.events
  queue: account.info.${server.port}
  dead-letter:
    exchange: account.info.dlx.${server.port}
    queue: account.info.dlq.${server.port}
axon:
  eventhandling:
    processors:
      info:
        source: amqpMessageSource
        mode: subscribing
        
---
spring:
  profiles: kafka
axon:
  eventhandling:
    processors:
      info:
        source: kafkaMessageSource
        mode: tracking
  kafka:
    bootstrap-servers: localhost:9092
    client-id: account-query-info
    default-topic: account.events
    properties:
      security.protocol: PLAINTEXT
    fetcher:
      poll-timeout: 3000                    #Default value
    consumer:
      group-id: account-query-info
      enable-auto-commit: true              #Enable auto-commit consumer offsets to the kafka server
      auto-commit-interval: 3000            #Auto-commit interval for consumer offsets
      
      
