{
 "title": "Account Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CreateAccountCommand counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(commandBus_CreateAccountCommand_failureCounter[30s])",
     "legendFormat": "CreateAccountCommand_failureCounter"
    },
    {
     "expr": "irate(commandBus_CreateAccountCommand_successCounter[30s])",
     "legendFormat": "CreateAccountCommand_successCounter"
    },
    {
     "expr": "irate(commandBus_CreateAccountCommand_ingestedCounter[30s])",
     "legendFormat": "CreateAccountCommand_ingestedCounter"
    }
   ]
  },
  {
   "title": "Event listeners capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_AccountCreatedEvent_1m_capacity",
     "legendFormat": "Balance_AccountCreatedEvent"
    },
    {
     "expr": "info_AccountCreatedEvent_1m_capacity",
     "legendFormat": "Info_AccountCreatedEvent_"
    },
    {
     "expr": "balance_AccountActivatedEvent_1m_capacity",
     "legendFormat": "Balance_AccountActivatedEvent"
    },
    {
     "expr": "info_AccountActivatedEvent_1m_capacity",
     "legendFormat": "Info_AccountActivatedEvent"
    }
   ]
  },
  {
   "title": "Event listener process time 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance_AccountCreatedEvent_1m_allTimer{quantile=\"0.5\"}",
     "legendFormat": "Balance_AccountCreatedEvent"
    },
    {
     "expr": "info_AccountCreatedEvent_1m_allTimer{quantile=\"0.5\"}",
     "legendFormat": "Info_AccountCreatedEvent_"
    },
    {
     "expr": "balance_AccountActivatedEvent_allTimer{quantile=\"0.5\"}",
     "legendFormat": "Balance_AccountActivatedEvent"
    },
    {
     "expr": "info_AccountActivatedEvent_1m_allTimer{quantile=\"0.5\"}",
     "legendFormat": "Info_AccountActivatedEvent"
    }
   ]
  }
 ]
}